### ISSUE TITLE
Using pybloqs instructions: misnamed variable

### ISSUE THREAD

**Issue by GeraldRushton** [manahl/PyBloqs#10]
https://github.com/manahl/PyBloqs#using-pybloqs

I think you meant to write

plot_block = Block(plt.plot(df['a'], df['b']))

not

plot = Block(plt.plot(df['a'], df['b']))

**Comment by DominikMChrist** [comment]
Good spot! Will make a change.

**Comment by DominikMChrist** [comment]
Fixed with release 1.0.2
