### ISSUE TITLE
Version Support and Platform Support

### ISSUE THREAD

**Issue by bmoscon** [manahl/PyBloqs#11]
You know its going to come up eventually, so at a minimum it would be nice if the documentation and setup.py script/PyPi were updated to indicate what platforms are supported (MacOS? Windows?) and what versions of Python are supported. I saw only 2.7 wheels/eggs on PyPi. Is Python3 supported?

**Comment by DominikMChrist** [comment]
I have successfully installed on Ubuntu, Win7 and MacOS both with and without HighCharts.
In terms of python version, it is Python 2.7 at present. Python3 is lower down my priority list at the moment, so this would be a great way for anyone to contribute to the development of PyBloqs.

**Comment by bmoscon** [comment]
Thanks. I think you can close this, it would just be nice if the documentation was updated :)

**Comment by pablojim** [comment]
Added versions doc in #12
