### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by tibhar940** [manahl/PyBloqs#28]
Please, add Python3 support in this module

**Comment by DominikMChrist** [comment]
Hi Alexey,

Thanks for your message. You are absolutely right, python3 support is something we definitely need. There was a bit of work to prepare for this, see https://github.com/manahl/PyBloqs/commit/afa7083e6faf4c54fce66bc1b0fd664122718ea2

It would be great if you could help with this task and contribute to the pybloqs code. I am happy to help with any issues along the way and getting you started.

Cheers,
Dominik

**Comment by bmoscon** [comment]
Its a huge undertaking - as I learned. There is a ton of code that uses py2 strings and doesnt work well with py3 bytes/unicode.

**Comment by sdabhi23** [comment]
@DominikMChrist @bmoscon I would like to collaborate on this. We can port the code in sections.

**Comment by DominikMChrist** [comment]
Hi, thank you very much for offering your help! In fact the work has already been done, thanks @HanTeo . Commit 07f88c1c is on master . We have not made the release of version 1.2 yet, that's why this issue has not been closed so far. Thanks again! Dominik

**Comment by DominikMChrist** [comment]
Finally released with PyBloqs 1.2.0

**Comment by HanTeo** [comment]
Woohoo
