### ISSUE TITLE
Cannot encode unicode characters when writing to pdf (python 2.7)

### ISSUE THREAD

**Issue by douglasbruce88** [manahl/PyBloqs#59]
When attempting to write a unicode character using wkhtmltox, the following error message is seen running on python2.7:

`UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 20: ordinal not in range(128)`

This appears to be because the base block no longer utf-8 encodes it's render output.

**Comment by DominikMChrist** [comment]
It's probably [this line](https://github.com/manahl/PyBloqs/blob/master/pybloqs/block/base.py#L165), which should have an encode='utf-8' parameter. Would you like to give it a try?

**Comment by douglasbruce88** [comment]
sure, will do. I'd tried on a different line in https://github.com/manahl/PyBloqs/commit/a088f4fed21aa2f861847130d74aa05bee942b1f but that's not quite working!

**Comment by Dainwright** [comment]
I think I have been experiencing this issue on Python3.6 and 3.7.

Since pulling 1.2.3 the issue has been fixed on both Python versions

**Comment by douglasbruce88** [comment]
Fixed in #60
